library("spssDDI");
setwd("/Users/timdavies/Documents/Business/Projects/Young Lives/Phase 2/code/IKMLinkedResearch/tools/spss_ddi_rdf/scripts")# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Ethiopia_R3-OlderChild-ET_OC_ChildLevel.sav");
sink("../data/ddi/Ethiopia_R3-OlderChild-ET_OC_ChildLevel.xml");
writeDDI(data,"../data/ddi/Ethiopia_R3-OlderChild-ET_OC_ChildLevel.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Ethiopia_R3-OlderChild-ET_OC_HouseholdLevel.sav");
sink("../data/ddi/Ethiopia_R3-OlderChild-ET_OC_HouseholdLevel.xml");
writeDDI(data,"../data/ddi/Ethiopia_R3-OlderChild-ET_OC_HouseholdLevel.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Ethiopia_R3-OlderChild-ET_OC_HouseholdMemberLevel.sav");
sink("../data/ddi/Ethiopia_R3-OlderChild-ET_OC_HouseholdMemberLevel.xml");
writeDDI(data,"../data/ddi/Ethiopia_R3-OlderChild-ET_OC_HouseholdMemberLevel.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Ethiopia_R3-OlderChild-stblHHSec3Crops.sav");
sink("../data/ddi/Ethiopia_R3-OlderChild-stblHHSec3Crops.xml");
writeDDI(data,"../data/ddi/Ethiopia_R3-OlderChild-stblHHSec3Crops.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Ethiopia_R3-OlderChild-stblHHSec3Loans.sav");
sink("../data/ddi/Ethiopia_R3-OlderChild-stblHHSec3Loans.xml");
writeDDI(data,"../data/ddi/Ethiopia_R3-OlderChild-stblHHSec3Loans.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Ethiopia_R3-OlderChild-stblHHSec3Outgoings.sav");
sink("../data/ddi/Ethiopia_R3-OlderChild-stblHHSec3Outgoings.xml");
writeDDI(data,"../data/ddi/Ethiopia_R3-OlderChild-stblHHSec3Outgoings.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Ethiopia_R3-OlderChild-stblHHSec3Plots.sav");
sink("../data/ddi/Ethiopia_R3-OlderChild-stblHHSec3Plots.xml");
writeDDI(data,"../data/ddi/Ethiopia_R3-OlderChild-stblHHSec3Plots.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Ethiopia_R3-OlderChild-stblHHSec3PlotsNoCrops.sav");
sink("../data/ddi/Ethiopia_R3-OlderChild-stblHHSec3PlotsNoCrops.xml");
writeDDI(data,"../data/ddi/Ethiopia_R3-OlderChild-stblHHSec3PlotsNoCrops.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Ethiopia_R3-OlderChild-stblHHSec3PlotsWithCrops.sav");
sink("../data/ddi/Ethiopia_R3-OlderChild-stblHHSec3PlotsWithCrops.xml");
writeDDI(data,"../data/ddi/Ethiopia_R3-OlderChild-stblHHSec3PlotsWithCrops.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Ethiopia_R3-OlderChild-stblHHSec3SupportProgrammes.sav");
sink("../data/ddi/Ethiopia_R3-OlderChild-stblHHSec3SupportProgrammes.xml");
writeDDI(data,"../data/ddi/Ethiopia_R3-OlderChild-stblHHSec3SupportProgrammes.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Ethiopia_R3-OlderChild-stblHHSec8ChildWork.sav");
sink("../data/ddi/Ethiopia_R3-OlderChild-stblHHSec8ChildWork.xml");
writeDDI(data,"../data/ddi/Ethiopia_R3-OlderChild-stblHHSec8ChildWork.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Ethiopia_R3-OlderChild-stblSec1Activities.sav");
sink("../data/ddi/Ethiopia_R3-OlderChild-stblSec1Activities.xml");
writeDDI(data,"../data/ddi/Ethiopia_R3-OlderChild-stblSec1Activities.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Ethiopia_R3-OlderChild-stblSec5Groups.sav");
sink("../data/ddi/Ethiopia_R3-OlderChild-stblSec5Groups.xml");
writeDDI(data,"../data/ddi/Ethiopia_R3-OlderChild-stblSec5Groups.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Ethiopia_R3-YoungerChild-ET_YC_ChildLevel.sav");
sink("../data/ddi/Ethiopia_R3-YoungerChild-ET_YC_ChildLevel.xml");
writeDDI(data,"../data/ddi/Ethiopia_R3-YoungerChild-ET_YC_ChildLevel.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Ethiopia_R3-YoungerChild-ET_YC_HouseholdLevel.sav");
sink("../data/ddi/Ethiopia_R3-YoungerChild-ET_YC_HouseholdLevel.xml");
writeDDI(data,"../data/ddi/Ethiopia_R3-YoungerChild-ET_YC_HouseholdLevel.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Ethiopia_R3-YoungerChild-ET_YC_HouseholdMemberLevel.sav");
sink("../data/ddi/Ethiopia_R3-YoungerChild-ET_YC_HouseholdMemberLevel.xml");
writeDDI(data,"../data/ddi/Ethiopia_R3-YoungerChild-ET_YC_HouseholdMemberLevel.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Ethiopia_R3-YoungerChild-stblHHSec3Crops.sav");
sink("../data/ddi/Ethiopia_R3-YoungerChild-stblHHSec3Crops.xml");
writeDDI(data,"../data/ddi/Ethiopia_R3-YoungerChild-stblHHSec3Crops.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Ethiopia_R3-YoungerChild-stblHHSec3Loans.sav");
sink("../data/ddi/Ethiopia_R3-YoungerChild-stblHHSec3Loans.xml");
writeDDI(data,"../data/ddi/Ethiopia_R3-YoungerChild-stblHHSec3Loans.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Ethiopia_R3-YoungerChild-stblHHSec3Outgoings.sav");
sink("../data/ddi/Ethiopia_R3-YoungerChild-stblHHSec3Outgoings.xml");
writeDDI(data,"../data/ddi/Ethiopia_R3-YoungerChild-stblHHSec3Outgoings.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Ethiopia_R3-YoungerChild-stblHHSec3Plots.sav");
sink("../data/ddi/Ethiopia_R3-YoungerChild-stblHHSec3Plots.xml");
writeDDI(data,"../data/ddi/Ethiopia_R3-YoungerChild-stblHHSec3Plots.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Ethiopia_R3-YoungerChild-stblHHSec3PlotsNoCrops.sav");
sink("../data/ddi/Ethiopia_R3-YoungerChild-stblHHSec3PlotsNoCrops.xml");
writeDDI(data,"../data/ddi/Ethiopia_R3-YoungerChild-stblHHSec3PlotsNoCrops.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Ethiopia_R3-YoungerChild-stblHHSec3PlotsWithCrops.sav");
sink("../data/ddi/Ethiopia_R3-YoungerChild-stblHHSec3PlotsWithCrops.xml");
writeDDI(data,"../data/ddi/Ethiopia_R3-YoungerChild-stblHHSec3PlotsWithCrops.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Ethiopia_R3-YoungerChild-stblHHSec3SupportProgrammes.sav");
sink("../data/ddi/Ethiopia_R3-YoungerChild-stblHHSec3SupportProgrammes.xml");
writeDDI(data,"../data/ddi/Ethiopia_R3-YoungerChild-stblHHSec3SupportProgrammes.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Ethiopia_R3-YoungerChild-stblHHSec8ChildWork.sav");
sink("../data/ddi/Ethiopia_R3-YoungerChild-stblHHSec8ChildWork.xml");
writeDDI(data,"../data/ddi/Ethiopia_R3-YoungerChild-stblHHSec8ChildWork.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Ethiopia_R3-YoungerChild-stblSec1Activities.sav");
sink("../data/ddi/Ethiopia_R3-YoungerChild-stblSec1Activities.xml");
writeDDI(data,"../data/ddi/Ethiopia_R3-YoungerChild-stblSec1Activities.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/India_R3-OlderChild-IN_OC_ChildLevel.sav");
sink("../data/ddi/India_R3-OlderChild-IN_OC_ChildLevel.xml");
writeDDI(data,"../data/ddi/India_R3-OlderChild-IN_OC_ChildLevel.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/India_R3-OlderChild-IN_OC_HouseholdLevel.sav");
sink("../data/ddi/India_R3-OlderChild-IN_OC_HouseholdLevel.xml");
writeDDI(data,"../data/ddi/India_R3-OlderChild-IN_OC_HouseholdLevel.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/India_R3-OlderChild-IN_OC_HouseholdMemberLevel.sav");
sink("../data/ddi/India_R3-OlderChild-IN_OC_HouseholdMemberLevel.xml");
writeDDI(data,"../data/ddi/India_R3-OlderChild-IN_OC_HouseholdMemberLevel.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/India_R3-OlderChild-stblHHSec3Crops.sav");
sink("../data/ddi/India_R3-OlderChild-stblHHSec3Crops.xml");
writeDDI(data,"../data/ddi/India_R3-OlderChild-stblHHSec3Crops.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/India_R3-OlderChild-stblHHSec3Outgoings.sav");
sink("../data/ddi/India_R3-OlderChild-stblHHSec3Outgoings.xml");
writeDDI(data,"../data/ddi/India_R3-OlderChild-stblHHSec3Outgoings.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/India_R3-OlderChild-stblHHSec3PrimaryAssets.sav");
sink("../data/ddi/India_R3-OlderChild-stblHHSec3PrimaryAssets.xml");
writeDDI(data,"../data/ddi/India_R3-OlderChild-stblHHSec3PrimaryAssets.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/India_R3-OlderChild-stblHHSec3SupportProgrammes.sav");
sink("../data/ddi/India_R3-OlderChild-stblHHSec3SupportProgrammes.xml");
writeDDI(data,"../data/ddi/India_R3-OlderChild-stblHHSec3SupportProgrammes.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/India_R3-OlderChild-stblSec1Activities.sav");
sink("../data/ddi/India_R3-OlderChild-stblSec1Activities.xml");
writeDDI(data,"../data/ddi/India_R3-OlderChild-stblSec1Activities.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/India_R3-OlderChild-stblSec5Groups.sav");
sink("../data/ddi/India_R3-OlderChild-stblSec5Groups.xml");
writeDDI(data,"../data/ddi/India_R3-OlderChild-stblSec5Groups.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/India_R3-YoungerChild-IN_YC_ChildLevel.sav");
sink("../data/ddi/India_R3-YoungerChild-IN_YC_ChildLevel.xml");
writeDDI(data,"../data/ddi/India_R3-YoungerChild-IN_YC_ChildLevel.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/India_R3-YoungerChild-IN_YC_HouseholdLevel.sav");
sink("../data/ddi/India_R3-YoungerChild-IN_YC_HouseholdLevel.xml");
writeDDI(data,"../data/ddi/India_R3-YoungerChild-IN_YC_HouseholdLevel.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/India_R3-YoungerChild-IN_YC_HouseholdMemberLevel.sav");
sink("../data/ddi/India_R3-YoungerChild-IN_YC_HouseholdMemberLevel.xml");
writeDDI(data,"../data/ddi/India_R3-YoungerChild-IN_YC_HouseholdMemberLevel.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/India_R3-YoungerChild-stblHHSec3Crops.sav");
sink("../data/ddi/India_R3-YoungerChild-stblHHSec3Crops.xml");
writeDDI(data,"../data/ddi/India_R3-YoungerChild-stblHHSec3Crops.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/India_R3-YoungerChild-stblHHSec3Outgoings.sav");
sink("../data/ddi/India_R3-YoungerChild-stblHHSec3Outgoings.xml");
writeDDI(data,"../data/ddi/India_R3-YoungerChild-stblHHSec3Outgoings.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/India_R3-YoungerChild-stblHHSec3PrimaryAssets.sav");
sink("../data/ddi/India_R3-YoungerChild-stblHHSec3PrimaryAssets.xml");
writeDDI(data,"../data/ddi/India_R3-YoungerChild-stblHHSec3PrimaryAssets.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/India_R3-YoungerChild-stblHHSec3SupportProgrammes.sav");
sink("../data/ddi/India_R3-YoungerChild-stblHHSec3SupportProgrammes.xml");
writeDDI(data,"../data/ddi/India_R3-YoungerChild-stblHHSec3SupportProgrammes.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/India_R3-YoungerChild-stblHHSec8ChildWork.sav");
sink("../data/ddi/India_R3-YoungerChild-stblHHSec8ChildWork.xml");
writeDDI(data,"../data/ddi/India_R3-YoungerChild-stblHHSec8ChildWork.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/India_R3-YoungerChild-stblSec1Activities.sav");
sink("../data/ddi/India_R3-YoungerChild-stblSec1Activities.xml");
writeDDI(data,"../data/ddi/India_R3-YoungerChild-stblSec1Activities.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Peru_R3-OlderChild-PE_OC_ChildLevel.sav");
sink("../data/ddi/Peru_R3-OlderChild-PE_OC_ChildLevel.xml");
writeDDI(data,"../data/ddi/Peru_R3-OlderChild-PE_OC_ChildLevel.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Peru_R3-OlderChild-PE_OC_HouseholdLevel.sav");
sink("../data/ddi/Peru_R3-OlderChild-PE_OC_HouseholdLevel.xml");
writeDDI(data,"../data/ddi/Peru_R3-OlderChild-PE_OC_HouseholdLevel.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Peru_R3-OlderChild-PE_OC_HouseholdMemberLevel.sav");
sink("../data/ddi/Peru_R3-OlderChild-PE_OC_HouseholdMemberLevel.xml");
writeDDI(data,"../data/ddi/Peru_R3-OlderChild-PE_OC_HouseholdMemberLevel.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Peru_R3-OlderChild-stblHHSec3Crops.sav");
sink("../data/ddi/Peru_R3-OlderChild-stblHHSec3Crops.xml");
writeDDI(data,"../data/ddi/Peru_R3-OlderChild-stblHHSec3Crops.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Peru_R3-OlderChild-stblHHSec3DailyWage.sav");
sink("../data/ddi/Peru_R3-OlderChild-stblHHSec3DailyWage.xml");
writeDDI(data,"../data/ddi/Peru_R3-OlderChild-stblHHSec3DailyWage.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Peru_R3-OlderChild-stblHHSec3DonatedFood.sav");
sink("../data/ddi/Peru_R3-OlderChild-stblHHSec3DonatedFood.xml");
writeDDI(data,"../data/ddi/Peru_R3-OlderChild-stblHHSec3DonatedFood.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Peru_R3-OlderChild-stblHHSec3MonetaryIncomes.sav");
sink("../data/ddi/Peru_R3-OlderChild-stblHHSec3MonetaryIncomes.xml");
writeDDI(data,"../data/ddi/Peru_R3-OlderChild-stblHHSec3MonetaryIncomes.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Peru_R3-OlderChild-stblHHSec3MonthlyWage.sav");
sink("../data/ddi/Peru_R3-OlderChild-stblHHSec3MonthlyWage.xml");
writeDDI(data,"../data/ddi/Peru_R3-OlderChild-stblHHSec3MonthlyWage.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Peru_R3-OlderChild-stblHHSec3NonMonEarnings.sav");
sink("../data/ddi/Peru_R3-OlderChild-stblHHSec3NonMonEarnings.xml");
writeDDI(data,"../data/ddi/Peru_R3-OlderChild-stblHHSec3NonMonEarnings.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Peru_R3-OlderChild-stblHHSec3PercMonetaryIncomes.sav");
sink("../data/ddi/Peru_R3-OlderChild-stblHHSec3PercMonetaryIncomes.xml");
writeDDI(data,"../data/ddi/Peru_R3-OlderChild-stblHHSec3PercMonetaryIncomes.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Peru_R3-OlderChild-stblHHSec3PercWageIncome.sav");
sink("../data/ddi/Peru_R3-OlderChild-stblHHSec3PercWageIncome.xml");
writeDDI(data,"../data/ddi/Peru_R3-OlderChild-stblHHSec3PercWageIncome.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Peru_R3-OlderChild-stblHHSec8ChildWork.sav");
sink("../data/ddi/Peru_R3-OlderChild-stblHHSec8ChildWork.xml");
writeDDI(data,"../data/ddi/Peru_R3-OlderChild-stblHHSec8ChildWork.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Peru_R3-OlderChild-stblSec1Activities.sav");
sink("../data/ddi/Peru_R3-OlderChild-stblSec1Activities.xml");
writeDDI(data,"../data/ddi/Peru_R3-OlderChild-stblSec1Activities.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Peru_R3-OlderChild-stblSec5Groups.sav");
sink("../data/ddi/Peru_R3-OlderChild-stblSec5Groups.xml");
writeDDI(data,"../data/ddi/Peru_R3-OlderChild-stblSec5Groups.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Peru_R3-YoungerChild-PE_YC_ChildLevel.sav");
sink("../data/ddi/Peru_R3-YoungerChild-PE_YC_ChildLevel.xml");
writeDDI(data,"../data/ddi/Peru_R3-YoungerChild-PE_YC_ChildLevel.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Peru_R3-YoungerChild-PE_YC_HouseholdLevel.sav");
sink("../data/ddi/Peru_R3-YoungerChild-PE_YC_HouseholdLevel.xml");
writeDDI(data,"../data/ddi/Peru_R3-YoungerChild-PE_YC_HouseholdLevel.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Peru_R3-YoungerChild-PE_YC_HouseholdMemberLevel.sav");
sink("../data/ddi/Peru_R3-YoungerChild-PE_YC_HouseholdMemberLevel.xml");
writeDDI(data,"../data/ddi/Peru_R3-YoungerChild-PE_YC_HouseholdMemberLevel.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Peru_R3-YoungerChild-stblHHSec3Crops.sav");
sink("../data/ddi/Peru_R3-YoungerChild-stblHHSec3Crops.xml");
writeDDI(data,"../data/ddi/Peru_R3-YoungerChild-stblHHSec3Crops.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Peru_R3-YoungerChild-stblHHSec3DailyWage.sav");
sink("../data/ddi/Peru_R3-YoungerChild-stblHHSec3DailyWage.xml");
writeDDI(data,"../data/ddi/Peru_R3-YoungerChild-stblHHSec3DailyWage.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Peru_R3-YoungerChild-stblHHSec3DonatedFood.sav");
sink("../data/ddi/Peru_R3-YoungerChild-stblHHSec3DonatedFood.xml");
writeDDI(data,"../data/ddi/Peru_R3-YoungerChild-stblHHSec3DonatedFood.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Peru_R3-YoungerChild-stblHHSec3MonetaryIncomes.sav");
sink("../data/ddi/Peru_R3-YoungerChild-stblHHSec3MonetaryIncomes.xml");
writeDDI(data,"../data/ddi/Peru_R3-YoungerChild-stblHHSec3MonetaryIncomes.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Peru_R3-YoungerChild-stblHHSec3MonthlyWage.sav");
sink("../data/ddi/Peru_R3-YoungerChild-stblHHSec3MonthlyWage.xml");
writeDDI(data,"../data/ddi/Peru_R3-YoungerChild-stblHHSec3MonthlyWage.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Peru_R3-YoungerChild-stblHHSec3NonMonEarnings.sav");
sink("../data/ddi/Peru_R3-YoungerChild-stblHHSec3NonMonEarnings.xml");
writeDDI(data,"../data/ddi/Peru_R3-YoungerChild-stblHHSec3NonMonEarnings.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Peru_R3-YoungerChild-stblHHSec3PercMonetaryIncomes.sav");
sink("../data/ddi/Peru_R3-YoungerChild-stblHHSec3PercMonetaryIncomes.xml");
writeDDI(data,"../data/ddi/Peru_R3-YoungerChild-stblHHSec3PercMonetaryIncomes.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Peru_R3-YoungerChild-stblHHSec3PercWageIncome.sav");
sink("../data/ddi/Peru_R3-YoungerChild-stblHHSec3PercWageIncome.xml");
writeDDI(data,"../data/ddi/Peru_R3-YoungerChild-stblHHSec3PercWageIncome.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Peru_R3-YoungerChild-stblHHSec8ChildWork.sav");
sink("../data/ddi/Peru_R3-YoungerChild-stblHHSec8ChildWork.xml");
writeDDI(data,"../data/ddi/Peru_R3-YoungerChild-stblHHSec8ChildWork.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Peru_R3-YoungerChild-stblSec1Activities.sav");
sink("../data/ddi/Peru_R3-YoungerChild-stblSec1Activities.xml");
writeDDI(data,"../data/ddi/Peru_R3-YoungerChild-stblSec1Activities.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Vietnam_R3-OlderChild-stblHHSec3Loans.sav");
sink("../data/ddi/Vietnam_R3-OlderChild-stblHHSec3Loans.xml");
writeDDI(data,"../data/ddi/Vietnam_R3-OlderChild-stblHHSec3Loans.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Vietnam_R3-OlderChild-stblHHSec3Outgoings.sav");
sink("../data/ddi/Vietnam_R3-OlderChild-stblHHSec3Outgoings.xml");
writeDDI(data,"../data/ddi/Vietnam_R3-OlderChild-stblHHSec3Outgoings.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Vietnam_R3-OlderChild-stblHHSec3PrimaryAssets.sav");
sink("../data/ddi/Vietnam_R3-OlderChild-stblHHSec3PrimaryAssets.xml");
writeDDI(data,"../data/ddi/Vietnam_R3-OlderChild-stblHHSec3PrimaryAssets.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Vietnam_R3-OlderChild-stblHHSec3SupportProgrammes.sav");
sink("../data/ddi/Vietnam_R3-OlderChild-stblHHSec3SupportProgrammes.xml");
writeDDI(data,"../data/ddi/Vietnam_R3-OlderChild-stblHHSec3SupportProgrammes.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Vietnam_R3-OlderChild-stblHHSec8ChildWork.sav");
sink("../data/ddi/Vietnam_R3-OlderChild-stblHHSec8ChildWork.xml");
writeDDI(data,"../data/ddi/Vietnam_R3-OlderChild-stblHHSec8ChildWork.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Vietnam_R3-OlderChild-stblSec1Activities.sav");
sink("../data/ddi/Vietnam_R3-OlderChild-stblSec1Activities.xml");
writeDDI(data,"../data/ddi/Vietnam_R3-OlderChild-stblSec1Activities.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Vietnam_R3-OlderChild-stblSec5Groups.sav");
sink("../data/ddi/Vietnam_R3-OlderChild-stblSec5Groups.xml");
writeDDI(data,"../data/ddi/Vietnam_R3-OlderChild-stblSec5Groups.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Vietnam_R3-OlderChild-VN_OC_ChildLevel.sav");
sink("../data/ddi/Vietnam_R3-OlderChild-VN_OC_ChildLevel.xml");
writeDDI(data,"../data/ddi/Vietnam_R3-OlderChild-VN_OC_ChildLevel.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Vietnam_R3-OlderChild-VN_OC_HouseholdLevel.sav");
sink("../data/ddi/Vietnam_R3-OlderChild-VN_OC_HouseholdLevel.xml");
writeDDI(data,"../data/ddi/Vietnam_R3-OlderChild-VN_OC_HouseholdLevel.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Vietnam_R3-OlderChild-VN_OC_HouseholdMemberLevel.sav");
sink("../data/ddi/Vietnam_R3-OlderChild-VN_OC_HouseholdMemberLevel.xml");
writeDDI(data,"../data/ddi/Vietnam_R3-OlderChild-VN_OC_HouseholdMemberLevel.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Vietnam_R3-YoungerChild-stblHHSec3Loans.sav");
sink("../data/ddi/Vietnam_R3-YoungerChild-stblHHSec3Loans.xml");
writeDDI(data,"../data/ddi/Vietnam_R3-YoungerChild-stblHHSec3Loans.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Vietnam_R3-YoungerChild-stblHHSec3Outgoings.sav");
sink("../data/ddi/Vietnam_R3-YoungerChild-stblHHSec3Outgoings.xml");
writeDDI(data,"../data/ddi/Vietnam_R3-YoungerChild-stblHHSec3Outgoings.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Vietnam_R3-YoungerChild-stblHHSec3PrimaryAssets.sav");
sink("../data/ddi/Vietnam_R3-YoungerChild-stblHHSec3PrimaryAssets.xml");
writeDDI(data,"../data/ddi/Vietnam_R3-YoungerChild-stblHHSec3PrimaryAssets.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Vietnam_R3-YoungerChild-stblHHSec3SupportProgrammes.sav");
sink("../data/ddi/Vietnam_R3-YoungerChild-stblHHSec3SupportProgrammes.xml");
writeDDI(data,"../data/ddi/Vietnam_R3-YoungerChild-stblHHSec3SupportProgrammes.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Vietnam_R3-YoungerChild-stblHHSec8ChildWork.sav");
sink("../data/ddi/Vietnam_R3-YoungerChild-stblHHSec8ChildWork.xml");
writeDDI(data,"../data/ddi/Vietnam_R3-YoungerChild-stblHHSec8ChildWork.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Vietnam_R3-YoungerChild-stblSec1Activities.sav");
sink("../data/ddi/Vietnam_R3-YoungerChild-stblSec1Activities.xml");
writeDDI(data,"../data/ddi/Vietnam_R3-YoungerChild-stblSec1Activities.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Vietnam_R3-YoungerChild-VN_YC_ChildLevel.sav");
sink("../data/ddi/Vietnam_R3-YoungerChild-VN_YC_ChildLevel.xml");
writeDDI(data,"../data/ddi/Vietnam_R3-YoungerChild-VN_YC_ChildLevel.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Vietnam_R3-YoungerChild-VN_YC_HouseholdLevel.sav");
sink("../data/ddi/Vietnam_R3-YoungerChild-VN_YC_HouseholdLevel.xml");
writeDDI(data,"../data/ddi/Vietnam_R3-YoungerChild-VN_YC_HouseholdLevel.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/Vietnam_R3-YoungerChild-VN_YC_HouseholdMemberLevel.sav");
sink("../data/ddi/Vietnam_R3-YoungerChild-VN_YC_HouseholdMemberLevel.xml");
writeDDI(data,"../data/ddi/Vietnam_R3-YoungerChild-VN_YC_HouseholdMemberLevel.xml");
sink();