<div style="text-align:center; width:740px; margin-left:auto; margin-right:auto;">
<img id="Image-Maps_7201202241137181" src="http://data.younglives.org.uk/uploads/Map.png" usemap="#Image-Maps_7201202241137181" border="0" width="740" height="382" alt="" />
<map id="_Image-Maps_7201202241137181" name="Image-Maps_7201202241137181">
<area shape="rect" coords="158,194,238,269" href="http://data.younglives.org.uk/pages/Peru.html" alt="Peru country page" title="Peru country page"    />
<area shape="rect" coords="381,181,461,256" href="http://data.younglives.org.uk/pages/Ethiopia.html" alt="Ethiopia country page" title="Ethiopia country page"    />
<area shape="rect" coords="469,139,536,212" href="http://data.younglives.org.uk/pages/India.html" alt="India country page" title="India country page"    />
<area shape="rect" coords="535,174,601,248" href="http://data.younglives.org.uk/pages/Vietnam.html" alt="Vietnam country page" title="Vietnam country page"    />
</map>
</div>
<h2>Young Lives Linked Data</h2>
<p>
Welcome to our pilot site that provides access to linked data from the Young Lives study. 
</p>
<p>
This is a pilot project to experiment with making a small sub-set of the <a href="http://www.younglives.org.uk">Young Lives Round 3 data</a> available for our users to manipulate and create their own graphs and charts. It has been funded by <a href="http://www.ikmemergent.net/" target="_blank">IKM-Emergent</a> (a programme that explores new ways of communicating about development issues) in order to investigate the pros and cons of using linked data methods with a micro-dataset. 
</p>
<p>
<a href="http://wikipedia.org/wiki/Linked_data" target="_blank">Linked data</a> is a form of publishing structured data so that it can be interlinked and become more useful. It uses web technologies to share information in a way that can be read automatically by computers. This enables data from different sources to be connected and queried.
</p>
<p>
Select a country above to view selected statistics and country information, or search or browse the available data from the options on the left. 
</p>
<p>
You can find out <a href="/pages/about.html">more about this site and it's use of linked data here</a>.
</p>

<p>
</p>
<h3>Young Lives Microdata</h3>
<p>
The full microdata datasets from Young Lives are also available for researchers to download from the UK Public Data Archive or on CD-rom from the Principal Investigators in each study country. See the '<a href="http://www.younglives.org.uk/what-we-do/access-our-data/access-our-data.html">Access our Data</a>' pages for details. 
</p>
